#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=99

USE_PROCD=1
PROG=/root/auto-ipset.sh

start_service() {
	procd_open_instance
	procd_set_param command "$PROG" btn https://github.com/PBH-BTN/BTN-Collected-Rules/raw/refs/heads/main/combine/all.txt
	procd_set_param respawn
	procd_close_instance
}
